stages:
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy:
  stage: deploy
  tags:
    - proxmox
  script:
    - cd /home/ppl/IF3250_K02_G10_IOM4
    - git pull origin main
    - docker compose down
    - docker compose build
        --build-arg NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
        --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
    - docker compose up -d
    - docker image prune -f